"""initial schema

Revision ID: c6ae2198463c
Revises: 
Create Date: 2026-06-14 10:44:31.477681
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c6ae2198463c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oidc_subject')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_household_id'), 'asset', ['household_id'], unique=False)
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('isbn10', sa.String(length=13), nullable=True),
    sa.Column('isbn13', sa.String(length=17), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('published_date', sa.String(length=40), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_source', sa.String(length=50), nullable=True),
    sa.Column('selected_cover_id', sa.Integer(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_cover_id'], ['cover_candidate.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_household_id'), 'book', ['household_id'], unique=False)
    op.create_index(op.f('ix_book_isbn10'), 'book', ['isbn10'], unique=False)
    op.create_index(op.f('ix_book_isbn13'), 'book', ['isbn13'], unique=False)
    op.create_index('ix_book_search_vector', 'book', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('household_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_invite_household_id'), 'household_invite', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_invite_token'), 'household_invite', ['token'], unique=True)
    op.create_table('household_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'household_id', name='uq_membership')
    )
    op.create_index(op.f('ix_household_membership_household_id'), 'household_membership', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_membership_user_id'), 'household_membership', ['user_id'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_household_id'), 'location', ['household_id'], unique=False)
    op.create_index(op.f('ix_location_parent_id'), 'location', ['parent_id'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_household_id'), 'person', ['household_id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'name', name='uq_tag_name')
    )
    op.create_index(op.f('ix_tag_household_id'), 'tag', ['household_id'], unique=False)
    op.create_table('book_tag',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'tag_id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_book_id'), 'comment', ['book_id'], unique=False)
    op.create_table('copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_book_id'), 'copy', ['book_id'], unique=False)
    op.create_index(op.f('ix_copy_household_id'), 'copy', ['household_id'], unique=False)
    op.create_index(op.f('ix_copy_location_id'), 'copy', ['location_id'], unique=False)
    op.create_table('cover_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_candidate_book_id'), 'cover_candidate', ['book_id'], unique=False)
    op.create_table('user_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_user_book')
    )
    op.create_index(op.f('ix_user_book_book_id'), 'user_book', ['book_id'], unique=False)
    op.create_index(op.f('ix_user_book_user_id'), 'user_book', ['user_id'], unique=False)
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copy_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('lender_user_id', sa.Integer(), nullable=True),
    sa.Column('lent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['copy_id'], ['copy.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lender_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_copy_id'), 'loan', ['copy_id'], unique=False)
    op.create_index(op.f('ix_loan_household_id'), 'loan', ['household_id'], unique=False)
    op.create_index(op.f('ix_loan_person_id'), 'loan', ['person_id'], unique=False)
    op.create_table('loan_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_feedback_loan_id'), 'loan_feedback', ['loan_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_feedback_loan_id'), table_name='loan_feedback')
    op.drop_table('loan_feedback')
    op.drop_index(op.f('ix_loan_person_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_household_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_copy_id'), table_name='loan')
    op.drop_table('loan')
    op.drop_index(op.f('ix_user_book_user_id'), table_name='user_book')
    op.drop_index(op.f('ix_user_book_book_id'), table_name='user_book')
    op.drop_table('user_book')
    op.drop_index(op.f('ix_cover_candidate_book_id'), table_name='cover_candidate')
    op.drop_table('cover_candidate')
    op.drop_index(op.f('ix_copy_location_id'), table_name='copy')
    op.drop_index(op.f('ix_copy_household_id'), table_name='copy')
    op.drop_index(op.f('ix_copy_book_id'), table_name='copy')
    op.drop_table('copy')
    op.drop_index(op.f('ix_comment_book_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_table('book_tag')
    op.drop_index(op.f('ix_tag_household_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_person_household_id'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_location_parent_id'), table_name='location')
    op.drop_index(op.f('ix_location_household_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_household_membership_user_id'), table_name='household_membership')
    op.drop_index(op.f('ix_household_membership_household_id'), table_name='household_membership')
    op.drop_table('household_membership')
    op.drop_index(op.f('ix_household_invite_token'), table_name='household_invite')
    op.drop_index(op.f('ix_household_invite_household_id'), table_name='household_invite')
    op.drop_table('household_invite')
    op.drop_index('ix_book_search_vector', table_name='book', postgresql_using='gin')
    op.drop_index(op.f('ix_book_isbn13'), table_name='book')
    op.drop_index(op.f('ix_book_isbn10'), table_name='book')
    op.drop_index(op.f('ix_book_household_id'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_asset_household_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('household')
    # ### end Alembic commands ###
