"""link person to user

Revision ID: e0c1416ddd91
Revises: 6e5b93858578
Create Date: 2026-06-14 16:12:04.134175
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e0c1416ddd91'
down_revision: str | None = '6e5b93858578'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_person_user_id'), 'person', ['user_id'], unique=False)
    op.create_foreign_key(None, 'person', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_index(op.f('ix_person_user_id'), table_name='person')
    op.drop_column('person', 'user_id')
    # ### end Alembic commands ###
